### ISSUE TITLE
Difference with Ucoslam

### ISSUE THREAD

**Issue by AndynWhen** [CarminLiu/ORB_SLAM2_aruco#1]
Can you give a brief introduce of the difference between this project and Ucoslam?

**Comment by CarminLiu** [comment]
Hi, 
It's just an implementation of UcoSLAM. Because part code(the main process) of UcoSLAM is encrypted, so I wrote the code base on the idea of this [paper](https://www.sciencedirect.com/science/article/pii/S0031320319304923).
There is  no big difference with UcoSLAM, but this: 1)simplifies the Loop Closure part. In other words, it can detect old Aruco but won't do loop clusure immediantely.  2)does not have the weight setting strategy of Aruco reprojection errors.
:)

**Comment by AndynWhen** [comment]
Got it. Thanks for reply!
